### ISSUE TITLE
Retry on failure

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/github-actions-demo#1]
If the Action fails, we should retry. Oakland CFS data is held for more than a day, but not by much.

**Comment by thejqs** [comment]
The tool we're using to pull data in this case is handling retries for us: https://github.com/openaddresses/pyesridump/blob/master/esridump/dumper.py#L19

We can override this and change that number, but I'm fairly confident that should be sufficient -- unless we find it's not. What might make more sense is closing this and creating a new issue for error reporting, so if it does fail for whatever reason, it's got some logging around it and we get an email. Then we can run it manually to get the resulting csv for that period and I can further investigate what sort of further resilience it might need.

**Comment by josh-chamberlain** [comment]
Oh, OK. I thought we did _not_ have retries, so I will close this
