### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/github-actions-demo#3]
If the Action fails, we should be notified so we can

- run it manually, if possible, to cover the outage
- fix it

I have no opinion on the contents of the log / email.

**Comment by thejqs** [comment]
Technically, I am receiving email reports when this Action fails. That's not everything we wanted, but what's left to accomplish in keeping this open, @josh-chamberlain?

**Comment by josh-chamberlain** [comment]
That's fine with me @thejqs, as long as there's a mechanism to alert you if it breaks
